Fix: change running scripts to script templates

diff --git a/run_test.sh.template b/run_test.sh.template
--- a/run_test.sh.template
+++ b/run_test.sh.template
@@ -1,15 +1,26 @@
 #!/bin/bash
+# 
+# A template for running LDBC test
 #
-# Usage: run_test.sh [DBNAME] [PORT] [USER] [DATAPATH]
+# Usage: Copy this template, modify the copied one to fill out information needed
+#        change its permission (chmod +x [filename]) and run it.
+#
+# Note:  The dataset should be already loaded before running this script
 
-DBNAME=$1
-PORT=$2
-USER=$3
-DATAPATH=$4
+# Modify this variables
+DBNAME=
+PORT=
+USER=
+DATAPATH=
 
-echo " ========================================= "
+echo " =================================== "
 echo " AgensGraph LDBC test running script "
-echo " ========================================= "
+echo " =================================== "
+
+if [ -z "$PORT" ] || [ -z "$USER" ] || [ -z "$DBNAME" ] || [ -z "$DATAPATH" ]; then 
+  echo "[ERROR] Fill out the empty variables (PORT, USER, DBNAME, DATAPATH)"
+  exit 1
+fi
 
 # It is highly recommended to add LDBC driver's default properties file 
 # using '-P' option in the following command 
@@ -19,6 +30,7 @@ echo " ========================================= "
 #
 
 java -cp target/classes/jeeves-0.3-SNAPSHOT.jar:target/classes/agensgraph-jdbc-0.9.0-SNAPSHOT.jar:target/classes com.ldbc.driver.Client \
+# -P ../ldbc_driver/configuration/ldbc/snb/interactive/ldbc_snb_interactive_SF-0001.properties 
 -P ldbc-test.properties \
 -p ldbc.snb.interactive.dbname $DBNAME \
 -p ldbc.snb.interactive.port $PORT \
diff --git a/run_validation.sh.template b/run_validation.sh.template
--- a/run_validation.sh.template
+++ b/run_validation.sh.template
@@ -1,16 +1,27 @@
 #!/bin/bash
+# 
+# A template for LDBC validation script
 #
-# Usage: run_validation.sh [PORT] [USER]
-# should be run by AgensGraph's superuser
+# Usage: Copy this template, modify the copied one to fill out information needed
+#        change its permission (chmod +x [filename]) and run it.
+#
+# Note:  This script should be run by AgensGraph's superuser
+#        because it will create a temp database (agensgraph_ldbc_validation)
 
-PORT=$1
-USER=$2
+# Modify this variables
+PORT=
+USER=
 DATAPATH=`pwd`/validation_set/social_network/num_date
 
 echo " ========================================= "
 echo " AgensGraph LDBC validation running script "
 echo " ========================================= "
 echo
+
+if [ -z "$PORT" ] || [ -z "$USER" ]; then 
+  echo "[ERROR] Fill out the empty variables (PORT, USER)."
+  exit 1
+fi
 
 if [ ! -d "validation_set" ];
 then
@@ -33,7 +44,8 @@ USER=$USER
 DATAPATH=$DATAPATH
 EOF
 
-./load.sh validation.conf
+load_queries/load.sh validation.conf
+rm -f validation.conf
 
 java -cp target/classes/jeeves-0.3-SNAPSHOT.jar:target/classes/agensgraph-jdbc-0.9.0-SNAPSHOT.jar:target/classes com.ldbc.driver.Client \
 -P validation.properties \
